# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.CharField(max_length=40)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.NullBooleanField(default=None)),
                ('captured_output', models.TextField()),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='ManagementCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('command', models.CharField(max_length=30, unique=True, verbose_name='Command')),
                ('max_minutes_to_run', models.IntegerField(blank=True, help_text="After this length of time, if we still haven't recorded that the command has finished, we assume something has gone wrong and it can be restarted again. Always make sure that the command can't take this long in normal use!", null=True, verbose_name='Maximum minutes to run')),
                ('currently_running', models.BooleanField(default=False, verbose_name='Currently running')),
                ('last_start', models.DateTimeField(blank=True, null=True, verbose_name='Time of last start')),
            ],
            options={
                'permissions': (('execute_managementcommand', 'Can execute management commands'),),
            },
        ),
        migrations.AddField(
            model_name='commandrun',
            name='management_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizard_management_command_runner.ManagementCommand'),
        ),
    ]
